server:
  port: 8086

spring:
  application:
    name: guli-08-statistics


#指定注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8084/eureka/
  instance:
    prefer-ip-address: true  #eureka服务器上获取的是服务器的ip地址，否则是主机名

